package com.flowerapp.hebasePayment.model;

import com.flowerapp.hebasePayment.domain.PaymentMethod;
import com.flowerapp.hebasePayment.domain.PaymentStatus;
import com.flowerapp.order.entity.Order;
import com.flowerapp.user.entity.User;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Table(name = "payments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique payment reference generated by our system
     */
    @Column(unique = true, nullable = false)
    private String paymentReference;

    /**
     * Hesabe payment token/ID
     */
    private String hesabePaymentId;

    /**
     * Hesabe checkout token
     */
    @Column(length = 1000)
    private String hesabeCheckoutToken;

    /**
     * Transaction ID from payment gateway
     */
    private String transactionId;

    /**
     * Order associated with this payment
     */
    @ManyToOne
    @JoinColumn(name = "order_id")
    private Order order;

    /**
     * User who made the payment
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * Payment method used
     */
    @Enumerated(EnumType.STRING)
    private PaymentMethod paymentMethod;

    /**
     * Payment status
     */
    @Enumerated(EnumType.STRING)
    private PaymentStatus status = PaymentStatus.PENDING;

    /**
     * Amount in the smallest currency unit (fils for KWD)
     */
    private Long amountInFils;

    /**
     * Amount in KWD
     */
    private Double amount;

    /**
     * Currency code
     */
    private String currency = "KWD";

    /**
     * Response code from Hesabe
     */
    private String responseCode;

    /**
     * Response message from Hesabe
     */
    @Column(length = 500)
    private String responseMessage;

    /**
     * Authorization code (for card payments)
     */
    private String authorizationCode;

    /**
     * Result code from payment gateway
     */
    private String resultCode;

    /**
     * Card details (masked)
     */
    private String maskedCardNumber;
    private String cardBrand;
    private String cardExpiryMonth;
    private String cardExpiryYear;

    /**
     * KNET specific fields
     */
    private String knetPaymentId;
    private String knetTransactionId;
    private String knetReferenceId;
    private String knetResultCode;

    /**
     * Checkout URL for redirect
     */
    @Column(length = 1000)
    private String checkoutUrl;

    /**
     * IP address of the customer
     */
    private String customerIpAddress;

    /**
     * Customer email
     */
    private String customerEmail;

    /**
     * Customer phone
     */
    private String customerPhone;

    /**
     * Timestamps
     */
    private LocalDateTime createdAt = LocalDateTime.now();
    private LocalDateTime updatedAt;
    private LocalDateTime completedAt;
    private LocalDateTime expiredAt;

    /**
     * Refund related fields
     */
    private boolean isRefunded = false;
    private Double refundAmount;
    private String refundReference;
    private LocalDateTime refundedAt;
    private String refundReason;

    /**
     * Additional metadata as JSON
     */
    @Column(columnDefinition = "TEXT")
    private String metadata;

    /**
     * Error details if payment failed
     */
    @Column(length = 1000)
    private String errorDetails;

    /**
     * Number of payment attempts
     */
    private int attempts = 1;

    /**
     * Webhook received
     */
    private boolean webhookReceived = false;
    private LocalDateTime webhookReceivedAt;

    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
